# Generated by Django 5.1.2 on 2024-11-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('answer', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('question', 'author')},
        ),
    ]
